name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: GIT_USER=edsonluiz CURRENT_BRANCH=master npm run publish-gh-pages
