
name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.16'

    - name: install
      working-directory: ./website
      run: npm install

    - name: deploy
      working-directory: ./website
      env:
        GIT_USER: edsonluiz
        CURRENT_BRANCH: master
      run: |
        npm run publish-gh-pages
