name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.16'

    - name: install
      working-directory: ./website
      run: npm install

    - name: build
      working-directory: ./website
      run: npm run build

    - name: deploy
      uses: peaceiris/actions-gh-pages@v2.3.0
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./website/build/javadevzone_web_test
